# vault configurations
[meta]
    # friendly name
    title =                 "My Awesome Package"
    # contributors
    author =                "Contributor Names"
    # version
    version =               "0.1.0"

# game-mode configurations
[game_mode]
    # whether to force the custom map package to do not load
    force_no_map_package =  false
    # auto destroy all entities spawned by this package when it unloads
    auto_cleanup =          true
    # whether to load all level entities on client - only enable it if your package needs to use level static meshes entities
    load_level_entities =   false
    # the game version (major.minor) at the time this package was created, for granting compatibility between breaking changes
    compatibility_version = "1.25"
    # packages requirements
    packages_requirements = [

    ]
    # asset packs requirements
    assets_requirements = [

    ]
    # compatible maps - maps to be highlighted when starting a new game through main menu
    compatible_maps = [

    ]

# game-mode custom settings configurations
# those settings can be overriden through new game menu and through command line
# and are accessed through Server.GetCustomSettings() method
[custom_settings]
    # my_toggle = { label = "awesome toggle", type = "boolean", description = "press this!", default = true }