# vault configurations
[meta]
    # friendly name
    title =                 "My Awesome Loading Screen"
    # contributors
    author =                "Contributor Names"
    # version
    version =               "0.1.0"

# loading-screen configurations
[loading_screen]
    # nothing here yet"