# vault configurations
[meta]
    # friendly name
    title =                 "My Awesome Asset Pack"
    # contributors
    author =                "Contributor Names"
    # version
    version =               "0.1.0"

# asset pack configurations
[asset_pack]
    # asset packs requirements
    assets_requirements = [

    ]

# unreal engine configurations
[unreal]
    # unreal engine folder - the name of the root folder (the one inside UnrealProject/Content/) which the assets will have references to each other
    unreal_folder =         "MyPack"
    # unreal engine version - unreal version this asset pack was compiled on
    unreal_version =        "5.1.0"
    # whether this asset pack was created as a plugin content"
    is_plugin_content =     false

# assets files
[assets]
    # maps
    [assets.maps]
        # MyMap = "MyFolder/MyAwesomeMap"
        # ...

    # static meshes
    [assets.static_meshes]
        # SM_Flower_01 = "MyFolder/SM_Awesome_Flower_01"
        # SM_Rock_01 = { path = "MyFolder/SM_Rock_01", my_tag = "something", thumbnail = "Thumbnails/SM_Rock_01.jpg" }
        # ...

    # skeletal meshes
    [assets.skeletal_meshes]
        # SK_Better_Man = "Characters/SK_BetterMan_0"
        # ...

    # sounds
    [assets.sounds]
        # A_My_Sound = "Sounds/A_My_Sound"
        # ...

    # animations
    [assets.animations]
        # A_Character_Jump = "Animations/A_Character_Jump"
        # ...

    # particles
    [assets.particles]
        # P_Big_Explosion = "Particles/P_Big_Explosion"
        # ...

    # materials
    [assets.materials]
        # M_Red_Textured = "Materials/M_Red_Textured"
        # ...

    # blueprints
    [assets.blueprints]
        # BP_Blueprint = "Blueprints/M_Red_Textured"
        # ...

    # other assets (for not yet categorized ones)
    [assets.others]
        # A_Audio_Rifle_Fire = "Audios/A_Audio_Rifle_Fire_03"
        # ...
