# map configurations
[map]
    # compatible game-modes
    compatible_game_modes = [
        "sandbox",
        "deathmatch"
    ]
    # the game version (major.minor) at the time this package was created, for granting compatibility between breaking changes
    compatibility_version = "1.29"
	# packages requirements
    packages_requirements = [

    ]
    # list of spawn points
    spawn_points = [
        { location = "Vector(100, 200, 100)", rotation = "Rotator(0, 90, 0)" },
        { location = "Vector(200, 300, 100)", rotation = "Rotator(0, 90, 0)" },
    ]

[custom_data]
    whatever = "anything"
	other_stuff = { awesome_key = "my value" }